type CalciteTheme =
  | "light"
  | "dark"

type CalciteColor = 
  | "lightest-blue"
  | "lighter-blue"
  | "blue"
  | "blue-dark"
  | "light-green"
  | "green"
  | "dark-green"
  | "light-red"
  | "red"
  | "dark-red"
  | "light-orange"
  | "orange"
  | "dark-orange"
  | "light-yellow"
  | "yellow"
  | "dark-yellow"
  | "light-purple"
  | "purple"
  | "dark-purple"
  | "light-brown"
  | "brown"
  | "dark-brown"
  /** grayscale */
  | "white"
  | "off-white"
  | "lightest-gray"
  | "lighter-gray"
  | "light-gray"
  | "gray"
  | "dark-gray"
  | "darker-gray"
  | "darkest-gray"
  | "black"
  | "off-black"
  | "transparent-black"

type ButtonModifier = 
  | "link"
  | "transparent"
  | "clear"
  | "clear-white"
  | "small"
  | "large"
  | "fill"
  | "half"
  | "disabled"

type CalciteIcon = 
  | "add-attachment"
  | "announcement"
  | "applications"
  | "arrow-down-circled"
  | "arrow-left-circled"
  | "arrow-right-circled"
  | "arrow-up-circled"
  | "attachment"
  | "authorize"
  | "basemap"
  | "beginning"
  | "blank-map-pin"
  | "browser"
  | "calculator"
  | "calendar"
  | "chart"
  | "chat"
  | "check-mark"
  | "checkbox-checked"
  | "checkbox-unchecked"
  | "close-circled"
  | "close"
  | "collapse"
  | "collection"
  | "comment"
  | "compass"
  | "configure-popup"
  | "contact"
  | "dashboard"
  | "deny"
  | "description"
  | "directions"
  | "directions2"
  | "dock-bottom"
  | "dock-left"
  | "dock-right"
  | "documentation"
  | "down-arrow-circled"
  | "down-arrow"
  | "down"
  | "download"
  | "drag-horizontal"
  | "drag-vertical"
  | "duplicate"
  | "edit"
  | "end"
  | "environment-settings"
  | "erase"
  | "error"
  | "error2"
  | "expand"
  | "experimental"
  | "favorites"
  | "feature-layer"
  | "filter"
  | "forward"
  | "globe"
  | "grant"
  | "grid"
  | "group"
  | "handle-horizontal"
  | "handle-vertical"
  | "home"
  | "key"
  | "labels"
  | "layer-list"
  | "layers"
  | "left-arrow-circled"
  | "left-arrow"
  | "left-triangle-arrow"
  | "left"
  | "line-chart"
  | "link-external"
  | "link"
  | "loading-indicator"
  | "locate"
  | "locked"
  | "map-pin"
  | "maps"
  | "marketplace"
  | "maximize"
  | "media"
  | "media2"
  | "menu"
  | "minimize"
  | "minus-circled"
  | "minus"
  | "mobile"
  | "navigation"
  | "notice-round"
  | "notice-triangle"
  | "organization"
  | "overview-arrow-bottom-left"
  | "overview-arrow-bottom-right"
  | "overview-arrow-top-left"
  | "overview-arrow-top-right"
  | "pan"
  | "pause"
  | "phone"
  | "pie-chart"
  | "play"
  | "plus-circled"
  | "plus"
  | "printer"
  | "question"
  | "radio-checked"
  | "radio-unchecked"
  | "refresh"
  | "resend-invitation"
  | "reverse"
  | "review"
  | "right-arrow-circled"
  | "right-arrow"
  | "right-triangle-arrow"
  | "right"
  | "rotate"
  | "save"
  | "search"
  | "settings"
  | "settings2"
  | "share"
  | "sign-out"
  | "sort-ascending"
  | "sort-descending"
  | "support"
  | "table"
  | "tag"
  | "time-clock"
  | "trash"
  | "unlocked"
  | "up-arrow-circled"
  | "up-arrow"
  | "up-down-arrows"
  | "up"
  | "upload"
  | "user"
  | "zoom-in-fixed"
  | "zoom-in-magnifying-glass"
  | "zoom-out-fixed"
  | "zoom-out-magnifying-glass"

type CalciteSocialIcon =
  | "contact"
  | "facebook"
  | "geonet"
  | "github"
  | "google-plus"
  | "instagram"
  | "linkedin"
  | "pinterest"
  | "rss"
  | "share"
  | "twitter"
  | "youtube"


  interface ICombineOptions {
    /** the component props */
    props: any;
    /** the prefix for the "appearance" prop */
    prefix: string,
    /** an array of other classes to use */
    baseClasses?: string[]
  }


interface ICalciteStyle {
  calciteClasses: Ref<string[]>; //ComputedRef<(string | Ref<string>)[]>;
  theme: Ref<CalciteTheme>;
}

interface ICalciteElmStyle {
  color?: CalciteColor;
  appearance?: string | ButtonModifier;
}

interface ICalciteElmStyleWithDisable extends ICalciteElmStyle {
  disabled?: boolean;
}

interface ICalciteButtonOptions extends ICalciteElmStyleWithDisable {
  label?: string;
}